"""Existing Panda pull actions, supplied as input to source-file migration.

Run: python migrate.py examples/panda_pull.py xarm6
This file contains only the source behavior. The target is generated by the LLM.
"""

from maniskill_backend.skill_adapter import ManiSkillPullCubeRobot

ENV_ID = "PullCube-v1"
SOURCE_ROBOT = "panda"
CONTROL_MODE = "pd_ee_delta_pos"

TASK_PROGRAM = '''
cube = scene.get_object("cube")
goal = scene.get_region("goal")
ret_val = robot.pull(cube, goal)
'''


def build_robot(env, *, control_mode, robot_uid):
    return ManiSkillPullCubeRobot(env, control_mode=control_mode, robot_uid=robot_uid)
